# Generated by Django 5.2.5 on 2025-08-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Descuento por porcentaje'), ('fijo', 'Descuento fijo')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('valido_desde', models.DateTimeField()),
                ('valido_hasta', models.DateTimeField()),
                ('total_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
