# Generated by Django 5.2.5 on 2025-08-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
