# Generated by Django 5.2.5 on 2025-08-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_itemcarrito_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
