# Generated by Django 5.2.5 on 2025-08-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cupon_alter_carrito_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='minimo_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total mínimo de compra para aplicar el cupón', max_digits=10),
        ),
    ]
