# Generated by Django 5.2.5 on 2025-09-01 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cupon_minimo_total'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.cupon'),
        ),
        migrations.DeleteModel(
            name='Cupon',
        ),
    ]
